<?php

namespace Tests\Feature;

use App\Account;
use App\Http\Resources\AccountResource;
use App\License;
use App\Sysadmin;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class LicenseTest extends TestCase
{

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->admin = factory(Sysadmin::class)->create();
        $this->be($this->admin,"sysadmin-api");
    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function test_crear_licencia()
    {
        $licencia = [
            "name" => "personalizado",
            "description" => "textotextotext",
            "lapse" => random_int(10, 50),
            "modules" => "monitoring",
            "units" => random_int(10, 500),
            "number_active_sessions" => random_int(1, 50)
        ];

        $call = $this->postJson( "api/sysadminv1/licenses", $licencia);

        $call->assertJsonStructure([
            "data" => [
                "lapse",
                "modules",
                "units",
                "number_active_sessions"
            ]
        ]);
        $call->assertStatus(200);
    }

    public function test_asignar_licencia_a_cuenta()
    {
        $license = factory(License::class)->create();
        $account = factory(Account::class)->create();

        $call = $this->postJson("api/sysadminv1/licenses/$license->id/assign_to_account", [
            "account_id" => $account->id
        ]);

        $call->assertSuccessful();

    }

    public function test_licencia_puede_ser_revocada()
    {
        $account = factory(Account::class)->create();
        $licencia = factory(License::class)->create();
        $account->addLicense($licencia);

        $call = $this->postJson("api/sysadminv1/licenses/{$licencia->id}/revoke", [
                "account_id" => $account->id
            ]);

        $call->assertSee("La licencia ha sido revocada");
        $this->assertDatabaseMissing("licenses_accounts", [
            "account_id" => $account->id,
            "license_id" => $licencia->id
        ]);
    }

    public function test_listar_licencias()
    {
        $call = $this->getJson("api/sysadminv1/licenses");

        $call->assertSuccessful();
    }

    public function test_ver_detalles_de_licencia()
    {
        $license = factory(License::class)->create();
        $call = $this->getJson("api/sysadminv1/licenses/{$license->id}");

        $call->assertSuccessful();
    }

}
