# docker image
image: laradock/workspace:2.6.1-7.3

# Pick zero or more services to be used on all builds.
services:
  - mariadb:latest

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: default
  MYSQL_USER: punksolid
  MYSQL_PASSWORD: 123ps123

before_script:
  # Update Composer
  - composer self-update

  # Install project dependencies.
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

  - chmod -R 775 storage
  - chmod 775 bootstrap/cache
  - chown -R www-data ./

  # Copy over testing configuration.
  - cp .env.gitlab .env

  # Generate an application key. Re-cache.
  - php artisan key:generate
  - php artisan cache:clear
  - php artisan config:clear
  - php artisan config:cache

  # Run database migrations.
  - php artisan migrate

code quality:
  stage: .pre
  script:
    - echo "Running PHPStan"
    - ls
#    - ./vendor/bin/phpstan --no-interaction --min-quality=70 --min-complexity=70 --min-architecture=70 --min-style=55


  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 1 days
    when: always

testing PHPUnit:
  stage: test
  script:
    # run tests
    - echo "Running PHPUnit Tests"
    - php artisan passport:install
    - php artisan key:generate
    - php artisan config:clear
    - php vendor/bin/phpunit --colors --testdox

  artifacts:
    paths:
      - ./storage/logs # for debugging
      # - ./tests/Browser/screenshots
      # - ./tests/Browser/console
    expire_in: 3 days
    when: always

deploy_to_development:
  stage: deploy
  script:
    - curl 'https://forge.laravel.com/servers/362453/sites/1002094/deploy/http?token=Zrg3vKTsPHbujz6yuC5VW06PyOFpJsERPwSGQNYh'

