# docker image
image: registry.gitlab.com/aknosis/laravel-ci-example:latest

# Pick zero or more services to be used on all builds.
services:
  - mysql:5.7

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: neotrm
  MYSQL_USER: punksolid
  MYSQL_PASSWORD: 123qwe123

before_script:
  # Update Composer
  - composer self-update

  # Install project dependencies.
  - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts

  - chmod -R 775 storage
  - chmod 775 bootstrap/cache
  - chown -R www-data ./

  # Copy over testing configuration.
  - cp .env.gitlab .env

  # Generate an application key. Re-cache.
  - php artisan key:generate
  - php artisan config:cache

  # Run database migrations.
  - php artisan migrate

  # Other configurations
  - start-nginx-ci-project

test:
  script:
    # run tests
    - echo "Running PHPUnit Tests"
    - php vendor/bin/phpunit --coverage-text --colors

  # - echo "Running Laravel Dusk"
  # - php artisan dusk --colors --debug

  artifacts:
    paths:
      - ./storage/logs # for debugging
      # - ./tests/Browser/screenshots
      # - ./tests/Browser/console
    expire_in: 7 days
    when: always
