branch-defaults:
  develop:
    environment: trm-dev
environment-defaults:
  trm-dev:
    branch: null
    repository: null
global:
  application_name: neotrm
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/PHP 7.1 running on
    64bit Amazon Linux/2.7.1
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
