<?php

namespace Tests\Feature;

use App\Account;
use App\Http\Middleware\LimitExpiredLicenseAccess;
use App\Http\Middleware\LimitSimoultaneousAccess;
use App\License;
use App\User;
use Carbon\Carbon;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class LoginTest extends TestCase
{

    protected function setUp():void
{
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = factory(User::class)->create();
    }

    public function test_acting_as()
    {
        $call = $this->actingAs($this->user,"api")->getJson("api/v1/me");
        $call->assertSee($this->user->email);

    }
    public function test_login_usuario()
    {
        $this->withoutExceptionHandling();
        $user = factory(User::class)->create();
        $call = $this->json("POST","/api/v1/login",[
            "email" => $user->email,
            "password" => "secret"
        ]);

        $call->assertJsonStructure([
            "access_token"
        ])
            ->assertStatus(200);
    }

    public function test_access_with_header_token()
    {
        $user = factory(User::class)->create();

        $call = $this->json("POST", "/api/v1/login",[
            "email" => $user->email,
            "password" => "secret"
        ]);
        $call->assertJsonStructure([
            "access_token",
            "token_type",
            "expires_at"
        ]);
        $token = $call->getOriginalContent()["access_token"];
        $call = $this->getJson("api/v1/me", ["Authorization" => "Bearer " . $token]);

        $call->assertStatus(200);
    }

    public function test_check_innaccesible_endpoint_for_not_logged_users()
    {
        $call = $this
            ->actingAs(factory(User::class)->create())
            ->getJson("api/v1/me");


        $call->assertStatus(401);

    }


}
