<?php

namespace Tests\Feature;

use App\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class MeTest extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = factory(User::class)->create();
        $this->actingAs($this->user, "api");
        $this->withoutMiddleware([LimitSimoultaneousAccess::class, LimitExpiredLicenseAccess::class]);

    }

    public function test_usuario_loggeado_debe_poder_cambiar_su_contrasenha()
    {
        $user = factory(User::class)->create();
        $call = $this->actingAs($user)->json("POST", "/api/v1/me/change_password", [
            "password" => "321321321",
            "password_confirmation" => "321321321"
        ]);

        $call->assertStatus(200);
    }
}
