<?php

namespace Tests\Feature;

use App\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class UsersTest extends TestCase
{
    var $user;


    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = factory(User::class)->create();
        $this->actingAs($this->user, "api");
        $this->withoutMiddleware([LimitSimoultaneousAccess::class, LimitExpiredLicenseAccess::class]);

    }

    public function test_se_puede_editar_un_usuario()
    {
        $user = factory(User::class)->create();
        $new_data = [
            "name" => $this->faker->name,
            "lastname" => $this->faker->lastName,
            "username" => $this->faker->userName,
            "email" => $this->faker->email,
            "password" => "123qwe"
        ];

        $call = $this->putJson("api/v1/users/{$user->id}", $new_data);
        unset($new_data["password"]);
        $call->assertJsonFragment($new_data);
    }
}
