<?php

namespace Tests\Feature;

use App\Http\Middleware\LimitExpiredLicenseAccess;
use App\Http\Middleware\LimitSimoultaneousAccess;
use App\User;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\Tenants\TestCase;

class UsersTest extends TestCase
{
    var $user;


    protected function setUp():void
{
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->user = factory(User::class)->create();
        $this->actingAs($this->user, "api");
        $this->withoutMiddleware([LimitSimoultaneousAccess::class, LimitExpiredLicenseAccess::class]);
        $this->withoutExceptionHandling();
        $this->withHeader("X-Tenant-Id", $this->account->uuid);
    }

    public function test_usuario_puede_registrar_otro_usuario()
    {
        $user = factory(User::class)->make();

        $call = $this->postJson('api/v1/users', [
            'email' => $user->email
        ]);


    }

    public function test_se_puede_editar_un_usuario()
    {
        $user = factory(User::class)->create();
        $new_data = [
            "name" => $this->faker->name,
            "lastname" => $this->faker->lastName,
            "username" => $this->faker->userName,
            "email" => $this->faker->email,
            "password" => "123qwe"
        ];

        $call = $this->putJson("api/v1/users/{$user->id}", $new_data);
        unset($new_data["password"]);
        $call->assertJsonFragment($new_data);

    }

    public function test_listar_usuarios()
    {
        $users = factory(User::class, 2)->create();
        $response = $this->getJson('/api/v1/users');

        $user1 = $users->first();
        $user2 = $users->last();
        $this->account->addUser($user1);
        $this->account->addUser($user2);

        $response
            ->assertJsonFragment([
                "email" => $user1->email
            ])
            ->assertJsonFragment([
                "email" => $user2->email
            ])
            ->assertStatus(200);

    }

    public function test_buscar_usuario_por_email()
    {
        $this->withoutExceptionHandling();
        $user_to_search = factory(User::class)->create();
        $this->account->addUser($user_to_search);
        $call = $this->getJson("api/v1/users?email=$user_to_search->email");

        $call->assertJsonFragment([
            "email" => $user_to_search->email
        ]);

        $user_to_search_2 = User::first();
        $this->account->addUser($user_to_search_2);

        $call = $this->getJson("api/v1/users?email=$user_to_search_2->email");

        $call->assertJsonFragment([
            "email" => $user_to_search_2->email
        ]);
    }

    public function test_search_username()
    {
        $this->withoutExceptionHandling();
        $user_to_search = factory(User::class)->create();
        $this->account->addUser($user_to_search);
        $user_to_search->profile()->create($profile = [
            "lastname" => $this->faker->lastName,
            "username" => $this->faker->userName
        ]);
        $user_to_search->with('profile')->get();


        $call = $this->getJson("api/v1/users?username={$profile['username']}");

        $call->assertJsonFragment([
            "username" => $profile['username']
        ]);

    }

    public function test_search_user_with_two_variables()
    {
        $this->withoutExceptionHandling();
        $user_to_search = factory(User::class)->create();
        $this->account->addUser($user_to_search);

        $user_to_search->profile()->create($profile = [
            "lastname" => $this->faker->lastName,
            "username" => $this->faker->userName
        ]);
        $user_to_search->with('profile')->get();

        $call = $this->getJson("api/v1/users?name={$user_to_search['name']}&lastname={$profile['lastname']}");

        $call->assertJsonFragment([
            "username" => $profile['username']
        ]);
    }

    public function test_usuario_puede_eliminar_usuario_de_su_plataforma()
    {
        $user = factory(User::class)->create();
        $this->account->addUser($user);

        $call = $this->deleteJson("api/v1/users/$user->id");

        $call->assertSuccessful();

        $this->assertFalse($this->account->userExists($user));
    }
}
