<?php

namespace Tests\Unit;


use App\Device;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Punksolid\Wialon\Unit;
use Punksolid\Wialon\Wialon;
use Tests\Tenants\TestCase;

class DeviceModelTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        config(["services.wialon.token" => "11b6e71f234078f1ca9e6944705a235bB6C1D1F551E3E263783A2354A63236306018E83E"]);
    }

    public function test_getLocation_returns_wialon_gps_data()
    {
        $this->markTestSkipped('Necesita token original');
        $unit = Unit::all()->first();
        $device = factory(Device::class)->create();
        $device->linkUnit($unit);
        
        $this->assertEquals($unit->lat,$device->getLocation()['lat']);
        $this->assertEquals($unit->lon,$device->getLocation()['lon']);
    }

    public function test_linked_method_verifies_on_wialon()
    {
        $device = new Device(['wialon_id' => '17471332']);

        $this->assertTrue($device->verifyConnection());
    }
}
